from typing import (
    Any,
    Dict,
    List, 
)

from printlm.agents.base import BaseAgent
from printlm.prompts.feedback.models import FeedbackPrompt
from printlm.prompts.task.models import TaskPrompt


class FeedbackAgent(BaseAgent):
    """
    Feedback agent class.
    """
    def __init__(
        self, 
        llm: Any,
        model_id: str, 
        **model_args,
    ) -> None:
        super().__init__(llm, model_id)
        self.model_args = model_args

    def _get_prompt(
        self,
        feedback_prompt: FeedbackPrompt,
        task_prompt: TaskPrompt,
        initial_code: str,
    ) -> List[Dict[str, str]]:
        """
        Get the (zero shot) prompt for the (chat) model.
        """
        messages = [
            {"role": feedback_prompt.role, "content": feedback_prompt.content},
            {"role": task_prompt.role, "content": f"{task_prompt.content} + \n + ### INCORRECT PYTHON CODE + \n {initial_code}"},
        ]
        return messages

    def _get_response(self,
        messages: List[Dict[str, str]],
        ) -> Any:
        """
        Get the response from the model.
        """
        response = self.llm(messages=messages, **self.model_args)
        return response
    
    def run(
        self, 
        feedback_prompt: FeedbackPrompt,
        task_prompt: TaskPrompt,
        initial_code: str,
    ) -> Dict[str, Any]:
        """Runs the Feedback agent

        Args:
            feedback_prompt (feedbackPrompt): The feedback prompt to use
            task_prompt (TaskPrompt): The task prompt to use
            initial_code (str): The initial code generated by the CodeAgent

        Returns:
            A dictionary containing the feedback model's response and the cost of the performed API call
        """
        # Get the prompt
        messages = self._get_prompt(feedback_prompt=feedback_prompt, task_prompt=task_prompt, initial_code=initial_code)
        # Get the response
        response = self._get_response(messages=messages)
        # Get Cost
        cost = self.calc_cost(response=response)

        return {
            'response': response,
            'response_str': response.choices[0].message.content,
            'cost': cost
        }